### ISSUE TITLE
有两个问题需要跟作者确认下~~

### ISSUE THREAD

**Issue by Yunnathai** [ianho/xing-weapp-component#1]
1.官方的scroll-view组件有假死情况  不知道解决没有？
复现情况，使用scroll-view组件后 在页面顶部上下滑几下  scroll-view随后就卡死不能滑动了，大概几秒后恢复
2.image组件  border-radius  莫名正方形问题解决了么，~？

**Comment by ianho** [comment]
第一个问题，我猜想是这样的，首先小程序本质是webview渲染网页（部分组件除外），所以这是一个手机网页的滑动问题，当你滑动某个可滑动的图层后，页面滑动图层会暂时锁定这个图层，此时无法滑动这个图层下可滑动的子图层，过一会会释放。原生的可能也有这个问题但我不确定
第二个问题我没碰到过，不过在我做的这个组件是组件本身通过overflow:hidden来实现圆角，并不对image本身设置圆角
